config/routes.rb
Rails.application.routes.draw do
  resources :psas, :except => :show do
    collection do
      get :lapsed
    end
  end
end

app/models/psa.rb
class Psa < ActiveRecord::Base
  scope :active, where('end_date is ? or end_date >= ?', nil, DateTime.now)
  scope :lapsed, where('not end_date is ? and end_date < ?',nil, DateTime.now)
  
  
  def route=(val)
    unless val.nil? || val.empty? || val =~ /^\^/ || val =~ /\$$/
      val = "^#{val}$"
    end
    val = nil if val.empty?
    write_attribute :route, val
  end
  
  def user_agent=(val)
    val = nil if val.empty?
    write_attribute :user_agent, val    
  end
  
  def to_s
    message
  end
end

app/controllers/psas_controller.rb
class PsasController < InheritedResources::Base
  include InheritedResources::DSL
  actions :all, :except => :show
  
  before_filter do
    if respond_to? :can_manage_psas?
      throw PublicSeriviceAnnouncement::AccessDenied.new unless can_manage_psas?
    end
  end
  
  create! do |success,failure|
    success.html{ redirect_to psas_path }
  end
  
  update! do |success,failure|
    success.html{ redirect_to psas_path }
  end
  
  def lapsed
    @psas = Psa.lapsed
    @status = 'lapsed'
    render 'index'
  end
  
  protected
  def collection
    @psas ||= Psa.active
  end
end

app/views/psas/_form.html.erb
<%= simple_form_for(@psa) do |f| %>
	<%= f.input :message %>
	<%= f.input :start_date %>
	<%= f.input :end_date, :default => DateTime.now + 10.years, :start_year => Date.today.year - 1 %>
	<%= f.input :max_views %>
	<%= f.input :route %>
	<%= f.input :user_agent %>
	<%= f.submit 'Save' %>
<%- end %>

app/views/psas/edit.html.erb
<%= render 'form' %>

app/views/psas/index.html.erb
<p>Showing <strong><%= @status || 'active' %></strong> announcements. Show <%= @status == "lapsed" ? link_to('active',psas_path) : link_to('lapsed', lapsed_psas_path) %> announcements.</p>

<%= link_to "New", new_psa_path %>

<table id="psas">
	<thead>
		<tr>
			<th></th>
			<th>Message</th>
			<th>Max Views</th>
			<th>Start Date</th>
			<th>End Date</th>
			<th>Route</th>
			<th>User Agent</th>
		</tr>
	</thead>
	<tbody>
		<% @psas.each do |psa| %>
		<tr class="<%= cycle('odd','even') %>">
			<td><%= link_to "Delete", psa, :method => :delete %> | <%= link_to "Edit", edit_psa_path(psa) %></td>
			<td><%= psa.message %></td>
			<td><%= psa.max_views %></td>
			<td><%= psa.start_date %></td>
			<td><%= psa.end_date %></td>
			<td><%= psa.route %></td>
			<td><%= psa.user_agent %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "New", new_psa_path %>

app/views/psas/new.html.erb
<% simple_form_for(@psa) do |f| %>
	<%= f.input :message %>
	<%= f.input :start_date %>
	<%= f.input :end_date, :default => DateTime.now + 10.years %>
	<%= f.input :max_views %>
	<%= f.input :route %>
	<%= f.input :user_agent %>
	<%= f.submit 'Save' %>
<% end %>